name: Deploy CV to Azure Static Web Apps

on:
  repository_dispatch:
    types: [cloudflare_tunnel_down]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          production_branch: main
